### ISSUE TITLE
panic_fmt in a dependency (apparently?) doesn’t work

### ISSUE THREAD

**Issue by SimonSapin** [jamesmunns/teensy3-rs#16] opened 2016-10-23 18:56 UTC
The `teensy3` crate defines:

``` rust
#[lang = "panic_fmt"]
pub extern fn rust_begin_panic(msg: core::fmt::Arguments, file: &'static str, line: u32) -> ! {
    println!("{:?}:{:?} - {:?}\n\r", file, line, msg);
    loop {}
}
```

When it is used as a Cargo dependency of `#![no_std]` executable (like `teensy3-demo`) it compiles fine, but the `println!` code doesn’t seem to be executed on panic when running on Teensy 3.2 hardware. Moving this function / lang item to the top-level crate (the one creating the executable program) "fixes" this problem.

**Comment by jamesmunns** [comment] 2016-10-24 00:42
Hey @SimonSapin - I can't seem to replicate your issue. Using a slightly modified example from the "teensy3-rs-demo" repo:

``` rust
#![no_std]
#![no_main]

#[macro_use]
extern crate teensy3;

use teensy3::bindings;
use teensy3::serial::Serial;

#[no_mangle]
pub unsafe extern fn main() {
    // Blink Loop

    bindings::pinMode(13, bindings::OUTPUT as u8);
    bindings::digitalWrite(13, bindings::LOW as u8);
    let mut ser = Serial{};

    for _ in 0..3 {
        // Show we are alive
        alive();

        // If the serial write fails, we will halt (no more alive blinks)
        hello(&ser).unwrap();

        // Don't spam the console
        bindings::delay(1000);
    }

    panic!("This is a panic!"); // This is line 29 in my source file
}

/// Blink the light twice to know we're alive
pub unsafe fn alive() {
    for _ in 0..2 {
        bindings::digitalWrite(13, bindings::LOW as u8);
        bindings::delay(200);
        bindings::digitalWrite(13, bindings::HIGH as u8);
        bindings::delay(200);
        bindings::digitalWrite(13, bindings::LOW as u8);
        bindings::delay(200);
    }
}

/// Send a message over the USB Serial port
pub fn hello(ser: &Serial) -> Result<(),()> {
    let msg = "Hello Teensy Rusty World!\n\r";
    ser.write_bytes(msg.as_bytes())
}
```

Heres the output:

``` bash
Hello Teensy Rusty World!
Hello Teensy Rusty World!
Hello Teensy Rusty World!
"src/main.rs":29 - This is a panic!
```

Heres my current version info:

```
➜  teensy3-rs-demo git:(master) ✗ rustc --version
rustc 1.14.0-nightly (098d22845 2016-10-13)
➜  teensy3-rs-demo git:(master) ✗ cargo --version
cargo 0.13.0-nightly (5f2cc15 2016-10-13)
```

And my lockfile

```
[root]
name = "teensy3-rs-demo"
version = "0.1.0"
dependencies = [
 "teensy3 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "teensy3"
version = "0.1.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "teensy3-sys 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "teensy3-sys"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[metadata]
"checksum teensy3 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = "3391d3bcd36087100f59f4d91577f3c4fe4919219e102ba87c$
"checksum teensy3-sys 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = "89d4d9e2b288386b21ec775e783bf1adf81ec2a4cbf777$
```

Let me know if anything looks odd for you. In your commit it looks like you are using teensy3 v0.1.2, not sure if that is an issue. Maybe try deleting your lockfile and see if that resolves the issue?

**Comment by SimonSapin** [comment] 2016-10-24 08:22
All right, I’ll try to make a minimal test case later.

(And `cargo update` seems less… "brutal" than deleting the lock file :))

**Comment by jamesmunns** [comment] 2016-11-04 02:06
@SimonSapin Any update, or is this okay to close?

**Comment by SimonSapin** [comment] 2016-11-04 08:31
I haven’t gotten around yet to trying to reproduce this, but feel free to close in the meantime.

**Comment by jamesmunns** [comment] 2016-11-05 19:56
Closing, reopen if you can give steps to reproduce :D

**Closed as completed by jamesmunns** 2016-11-05 19:56 UTC
