### ISSUE TITLE
Supporting more Teensy hardware

### ISSUE THREAD

**Issue by TheZoq2** [jamesmunns/teensy3-rs#14] opened 2016-10-11 16:34 UTC
How hard would it be to add support for more teensy devices like the teensy LC or the newly released 3.1/3.2? 

I would love to mess around with this and I have some of those laying around but no 3.1/3.2

**Comment by jamesmunns** [comment] 2016-10-12 21:00
Hey, there is already support for the 3.1/3.2, and an issue open for the 3.0. There is also an issue open for the 3.5/3.6 support, but I should probably split that from the 3.0, as the task will be a little different.

I believe the Teensy LC uses a processor that is similar, but will probably also require its own set of work. Off the top of my head, it will probably be necessary to re-run servo bindgen for each of the new targets.

I will be working on this issue: https://github.com/jamesmunns/teensy3-rs/issues/9 this weekend hopefully, I would suggest following there. I'll keep the LC in mind while I work on those changes to see if I can handle both at once.

**Comment by SimonSapin** [comment] 2017-04-17 15:48
Let’s call this a duplicate of #9.

**Closed as completed by SimonSapin** 2017-04-17 15:48 UTC
